site_name: SmileSherlock
site_url: https://smilesherlock.readthedocs.io
repo_url: https://github.com/AtharvaTilewale/SmileSherlock
site_description: High-performance SMILES validation and PubChem lookup.

theme:
  name: material
  logo: docs/assets/smilesherlock-logo.png
  favicon: docs/assets/smilesherlock-logo.png
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
  palette:
    # Provides a sleek dark-mode by default
    scheme: slate
    primary: indigo
    accent: blue

nav:
  - Home: index.md
  - Practical Guide: practical_guide.md
  - API Reference: api_reference.md
  - Configuration: configuration.md
  - Changelog: changelog.md
  - Contributing: contributing.md