"""IUPAC name generation from SMILES strings.

Uses a multi-tier approach:
    1. OFFLINE  — RDKit generates InChI and InChIKey (fully offline, IUPAC standard).
    2. CACHE    — If a PubChem lookup was previously cached in SQLite, return stored name.
    3. ONLINE   — Fetch IUPAC preferred name from PubChem REST API (opt-in via use_online).

The InChI (International Chemical Identifier) is itself an IUPAC-endorsed systematic
identifier. For small molecules, the PubChem preferred name is the human-readable
IUPAC systematic name generated by OPSIN on PubChem's servers.
"""

from __future__ import annotations

import json
import urllib.error
import urllib.request
from typing import Optional

from pydantic import BaseModel, Field

try:
    from rdkit import Chem
    from rdkit.Chem import Descriptors, rdMolDescriptors
    from rdkit.Chem.inchi import MolToInchi, InchiToInchiKey

    _RDKIT_AVAILABLE = True
except ImportError:
    _RDKIT_AVAILABLE = False


class IUPACResult(BaseModel):
    """Result of IUPAC name generation from a SMILES string."""

    input_smiles: str
    canonical_smiles: Optional[str] = None
    molecular_formula: Optional[str] = None
    molecular_weight: Optional[float] = None
    inchi: Optional[str] = None
    inchikey: Optional[str] = None
    iupac_name: Optional[str] = None
    iupac_name_source: str = "none"  # "offline_inchi" | "cache" | "pubchem" | "none"
    error: Optional[str] = None


def get_iupac_name(
    smiles: str,
    use_online: bool = False,
    cache_db_path: Optional[str] = None,
) -> IUPACResult:
    """Generate systematic identifiers and optionally fetch IUPAC name for a SMILES string.

    Args:
        smiles:         Input SMILES string.
        use_online:     If True, fetch the IUPAC preferred name from PubChem API
                        and cache it locally for future offline use.
        cache_db_path:  Path to the SQLite cache database. Defaults to the global
                        SmileSherlock settings cache.

    Returns:
        IUPACResult with InChI, InChIKey, formula, MW, and IUPAC name if available.
    """
    if not _RDKIT_AVAILABLE:
        return IUPACResult(
            input_smiles=smiles,
            error="RDKit is not installed. Install it with: pip install rdkit",
        )

    # Parse and validate SMILES
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return IUPACResult(
            input_smiles=smiles,
            error=f"Invalid SMILES: could not parse '{smiles}'",
        )

    # Offline step: compute properties and InChI
    canonical_smiles = Chem.MolToSmiles(mol)
    formula = rdMolDescriptors.CalcMolFormula(mol)
    mw = round(Descriptors.ExactMolWt(mol), 4)

    inchi = None
    inchikey = None
    try:
        inchi = MolToInchi(mol)
        if inchi:
            inchikey = InchiToInchiKey(inchi)
    except Exception:
        pass

    result = IUPACResult(
        input_smiles=smiles,
        canonical_smiles=canonical_smiles,
        molecular_formula=formula,
        molecular_weight=mw,
        inchi=inchi,
        inchikey=inchikey,
        iupac_name_source="offline_inchi",
    )

    # Cache lookup (SQLite)
    iupac_name = _check_cache(canonical_smiles, cache_db_path)
    if iupac_name:
        result.iupac_name = iupac_name
        result.iupac_name_source = "cache"
        return result

    # Online fetch from PubChem
    if use_online:
        name, source = _fetch_from_pubchem(canonical_smiles, inchikey)
        if name:
            result.iupac_name = name
            result.iupac_name_source = source
            _store_cache(canonical_smiles, name, cache_db_path)
        else:
            result.iupac_name = None

    return result


# ─── Cache helpers ────────────────────────────────────────────────────────────

def _get_cache_db_path(cache_db_path: Optional[str]) -> Optional[str]:
    """Resolve the cache database path."""
    if cache_db_path:
        return cache_db_path
    try:
        from smilesherlock.config import settings
        return str(settings.db_path)
    except Exception:
        return None


def _check_cache(canonical_smiles: str, cache_db_path: Optional[str]) -> Optional[str]:
    """Look up IUPAC name in the local SQLite cache."""
    db_path = _get_cache_db_path(cache_db_path)
    if not db_path:
        return None
    try:
        import sqlite3
        with sqlite3.connect(db_path) as conn:
            conn.execute(
                """CREATE TABLE IF NOT EXISTS iupac_names
                   (smiles TEXT PRIMARY KEY, iupac_name TEXT, created_at TEXT)"""
            )
            row = conn.execute(
                "SELECT iupac_name FROM iupac_names WHERE smiles = ?",
                (canonical_smiles,),
            ).fetchone()
            return row[0] if row else None
    except Exception:
        return None


def _store_cache(canonical_smiles: str, iupac_name: str, cache_db_path: Optional[str]) -> None:
    """Store a newly fetched IUPAC name in the local SQLite cache."""
    db_path = _get_cache_db_path(cache_db_path)
    if not db_path:
        return
    try:
        import sqlite3
        from datetime import datetime, timezone
        with sqlite3.connect(db_path) as conn:
            conn.execute(
                """CREATE TABLE IF NOT EXISTS iupac_names
                   (smiles TEXT PRIMARY KEY, iupac_name TEXT, created_at TEXT)"""
            )
            conn.execute(
                """INSERT OR REPLACE INTO iupac_names (smiles, iupac_name, created_at)
                   VALUES (?, ?, ?)""",
                (canonical_smiles, iupac_name, datetime.now(timezone.utc).isoformat()),
            )
            conn.commit()
    except Exception:
        pass


def _fetch_from_pubchem(canonical_smiles: str, inchikey: Optional[str]) -> tuple[Optional[str], str]:
    """Fetch the IUPAC preferred name from PubChem REST API.

    Returns (name, source_label) or (None, "none").
    """
    # Try by SMILES first (URL-safe encode)
    urls_to_try = []
    try:
        import urllib.parse
        encoded = urllib.parse.quote(canonical_smiles, safe="")
        urls_to_try.append(
            (f"https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/smiles/{encoded}/property/IUPACName/JSON", "pubchem")
        )
    except Exception:
        pass

    # Fallback: try by InChIKey (more stable URL)
    if inchikey:
        urls_to_try.append(
            (f"https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/inchikey/{inchikey}/property/IUPACName/JSON", "pubchem")
        )

    for url, source in urls_to_try:
        try:
            with urllib.request.urlopen(url, timeout=8) as resp:
                data = json.loads(resp.read().decode())
            props = data.get("PropertyTable", {}).get("Properties", [])
            if props:
                name = props[0].get("IUPACName")
                if name:
                    return name, source
        except (urllib.error.URLError, json.JSONDecodeError, KeyError):
            continue
        except Exception:
            continue

    return None, "none"
